name: Publish new version on NPM

on:
  branches:
    - next
    - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: git fetch --progress --depth=1 origin ${{ github.base_ref }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm test

  build_and_publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run build
